name: Blog CI/CD

# 觸發條件：在 push 到 hexo-blog-backup 分支後觸發
on:
  push:
    branches: 
      - hexo

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系統作為編譯部署的環境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 設定 node.js 環境
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      # 設定包快取目錄，避免每次下載
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下載 hexo-cli 腳手架及相關安裝包
      run: |
        npm install hexo-cli gulp -g
        npm install

    - name: Generate files
      # 編譯 markdown 檔案
      run: |
        hexo clean
        hexo generate

    - name: Execute gulp task
      run: gulp

    - name: Deploy hexo blog
      env: 
        # Github 倉庫
        GITHUB_REPO: github.com/chianChen/chianChen2.github.io
        # Coding 倉庫
        # CODING_REPO: e.coding.net/yifanzheng/blogs.git
        # Gitee 倉庫
        # GITEE_REPO: gitee.com/yifanzheng/yifanzheng.gitee.io
      # 將編譯後的部落格檔案推送到指定倉庫
      run: |
        cd ./public && git init && git add .
        git config user.name "chianChen"
        git config user.email "joseph8225@outlook.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
        # git push --force --quiet "https://RoYFbFDSfM:${{ secrets.CODING_TOKEN }}@$CODING_REPO" master:master
        git push --force --quiet "https://chianChen:${{ secrets.GITEE_ACCESS_TOKEN }}@$GITEE_REPO" master:master
